### ISSUE TITLE
Specifying launch with URL fails with "Can't find a target that matches"

### ISSUE THREAD

**Issue by mattdsteele** [Microsoft/vscode-ios-web-debug#11]
Running Windows 7; have the latest iTunes installed, iPhone 4S with iOS 9.3.5. I think the rest of my environment is in the debug console.

My launch configuration:

My project is accessible on my workstation via `localhost:1234/docs/index.html`

When I try launching the project, nothing happens on my phone, and I get this error:

```
[debugger-for-chrome] Can't find a target that matches: /docs/index.html. Available pages: ["about:blank"]
```

```
        {
            "name": "Navigate to current project on an iOS device",
            "type": "ios",
            "request": "launch",
            "port": 9222,
            "url": "/docs/index.html",
            "webRoot": "${workspaceRoot}",
            "deviceName": "*",
            "diagnosticLogging": true,
            "sourceMaps": true,
            "tunnelPort": 1234
        },
```

My debug console:

```
 ›OS: win32 ia32
  ›Node: v5.10.0
  ›vscode-chrome-debug-core: 0.1.16
  ›debugger-for-ios-web: 0.1.2
  ›Launching localtunnel against port 1234
  ›spawn('C:\Users\IGEN261\.vscode-oss\extensions\msjsdiag.debugger-for-ios-web-0.1.2\node_modules\vs-libimobile\lib\ios_webkit_debug_proxy.exe', ["--no-frontend","--config=null:9222,:9223-9323"])
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Success.1234
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Discovering targets via http://127.0.0.1:9223/json
  ›Error: Can't find a target that matches: /docs/index.html. Available pages: ["about:blank"]
    at _selectTarget (C:\Users\IGEN261\.vscode-oss\extensions\msjsdiag.debugger-for-ios-web-0.1.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeTargetDiscoveryStrategy.js:48:19)
    at C:\Users\IGEN261\.vscode-oss\extensions\msjsdiag.debugger-for-ios-web-0.1.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeTargetDiscoveryStrategy.js:15:22
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Any idea what might be going on?

**Comment by hoovercj** [comment]
By chance do you have chrome open on the machine? I found that having chrome open caused problems for me.

**Comment by Gatunox** [comment]
Yes, That's the problem. It launches the new Instance but it seems it tries to connect to the previous one, therefore i was getting the error, Once i close the existing running instance it works
This is my json.

`{
    "version": "0.1.0",
    "configurations": [ 
        {
            "name": "Launch index.html (disable sourcemaps)",
            "type": "chrome",
            "request": "launch",
            "sourceMaps": false,
            "file": "${workspaceRoot}/index.html"
        }
    ]
}`

**Comment by leonid-shevtsov** [comment]
Workaround: specify a different `port` option for every configuration.
