### ISSUE TITLE
iOS 10 Support?

### ISSUE THREAD

**Issue by troysandal** [Microsoft/vscode-ios-web-debug#14]
Would really love to use this but something tells me it doesn't like iOS 10, am I wrong?  I can connect / debug my phone just fine via Safari desktop but VSC won't connect.  Have read others having iOS 10 issues, let me know what else to try.

```
›OS: darwin x64
  ›Node: v6.5.0
  ›vscode-chrome-debug-core: 0.1.16
  ›debugger-for-ios-web: 0.1.2
  ›spawn('/usr/local/bin/ios_webkit_debug_proxy', ["--no-frontend","--config=null:9222,:9223-9323"])
  ›Discovering targets via http://127.0.0.1:9222/json
  ...
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Discovering targets via http://127.0.0.1:9222/json
  ›Error: Got a response from the target app, but no target pages found
    at Object.errP (/Users/troy/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/utils.js:225:13)
    at /Users/troy/.vscode/extensions/msjsdiag.debugger-for-ios-web-0.1.2/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeTargetDiscoveryStrategy.js:13:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

My launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Navigate to current project on an iOS device",
            "type": "ios",
            "request": "launch",
            "port": 9222,
            "diagnosticLogging": true,
            "url": "/test.html",
            "webRoot": "${workspaceRoot}/public",
            "deviceName": "*",
            "tunnelPort": 3000
        },
        {
            "name": "Navigate to url on an iOS device",
            "type": "ios",
            "request": "launch",
            "port": 9222,
            "diagnosticLogging": true,
            "url": "http://mysite.com/test.html",
            "webRoot": "${workspaceRoot}/public",
            "deviceName": "*"
        },
        {
            "name": "Attach to an iOS device",
            "type": "ios",
            "request": "attach",
            "url": "/test.html",
            "port": 9222,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}/public",
            "deviceName": "*"
        }
    ]
}
```

**Comment by auchenberg** [comment]
iOS 10 should be supported if you use the latest `head` version of `ios-webkit-debug-proxy`

```
brew install libimobiledevice --HEAD
brew install ios-webkit-debug-proxy --HEAD
```

There's several issues related to iOS 10 for the adapter, which this debugger relies on. https://github.com/google/ios-webkit-debug-proxy/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ios%2010
